menu:
- {name: '团队', url: '/team'}
# - {name: 'publications', url: '/publications'}
- {name: '获奖', url: '/awards'}
- {name: '授课', url: '/teaching'}
# - {name: 'cv', url: '/cv'}
- {name: '加入我们', url: '/joinus'}
- {name: '联系我们', url: '/contact'}
# - {name: 'EN', url: ''}


people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

# courses:
# - {name: 'Vector Calculus', url: 'vector-calculus'}
# - {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
# - {name: 'Stellar Structures', url: 'stellar-structures'}

classof2023: 
# - {name: 'Kangjie BAO', school: 'School of Mathematical Sciences', image: 'assets/img/classof2023/baokangjie.png', url: ''}
# - {name: 'Zicong CHENG', school: 'School of Electronic Information and Electrical Engineering', image: 'assets/img/classof2023/chengzicong.png', url: ''}
- {name: '鲍康捷', school: '数学科学学院', image: 'assets/img/classof2023/baokangjie.png', url: ''}
- {name: '程子枞', school: '电子信息与电气工程学院', image: 'assets/img/classof2023/chengzicong.png', url: ''}
- {name: '高珊', school: '电子信息与电气工程学院', image: 'assets/img/classof2023/gaoshan.png', url: ''}
- {name: '葛睿', school: '电子信息与电气工程学院', image: 'assets/img/classof2023/gerui.png', url: ''}
- {name: '郭宇涵', school: '电子信息与电气工程学院', image: 'assets/img/classof2023/guoyuhan.png', url: ''}
- {name: '孔珺晓', school: '电子信息与电气工程学院', image: 'assets/img/classof2023/kongjunxiao.png', url: ''}
- {name: '李东校', school: '巴黎卓越工程师学院', image: 'assets/img/classof2023/lidongxiao.png', url: ''}
- {name: '刘继泽', school: '电子信息与电气工程学院', image: 'assets/img/classof2023/liujize.png', url: ''}
- {name: '刘伊天', school: '电子信息与电气工程学院', image: 'assets/img/classof2023/liuyitian.png', url: ''}
- {name: '卢嘉成', school: '安泰经济与管理学院', image: 'assets/img/classof2023/lujiacheng.png', url: ''}
- {name: '彭泽瑞', school: '电子信息与电气工程学院', image: 'assets/img/classof2023/pengzerui.png', url: ''}
- {name: '邱博林', school: '电子信息与电气工程学院', image: 'assets/img/classof2023/qiubolin.png', url: ''}
- {name: '阮亿康', school: '电子信息与电气工程学院', image: 'assets/img/classof2023/ruanyikang.png', url: ''}
- {name: '帅哲', school: '设计学院', image: 'assets/img/classof2023/shuaizhe.png', url: ''}
- {name: '童欣文', school: '电子信息与电气工程学院', image: 'assets/img/classof2023/tongxinwen.png', url: ''}
- {name: '王雨杭', school: '电子信息与电气工程学院', image: 'assets/img/classof2023/wangyuhang.png', url: ''}
- {name: '夏欣媛', school: '电子信息与电气工程学院', image: 'assets/img/classof2023/xiaxinyuan.png', url: ''}
- {name: '徐聪晟', school: '电子信息与电气工程学院', image: 'assets/img/classof2023/xucongsheng.png', url: ''}
- {name: '许禾翌', school: '设计学院', image: 'assets/img/classof2023/xuheyi.png', url: ''}
- {name: '阎冠举', school: '物理与天文学院', image: 'assets/img/classof2023/yanguanju.png', url: ''}
- {name: '曾奕锟', school: '电子信息与电气工程学院', image: 'assets/img/classof2023/zengyikun.png', url: ''}
- {name: '张家硕', school: '数学科学学院', image: 'assets/img/classof2023/zhangjiashuo.png', url: ''}
- {name: '张文康', school: '电子信息与电气工程学院', image: 'assets/img/classof2023/zhangwenkang.png', url: ''}
- {name: '赵妤', school: '电子信息与电气工程学院', image: 'assets/img/classof2023/zhaoyu.png', url: ''}
- {name: '周溢茂', school: '人文学院', image: 'assets/img/classof2023/zhouyimao.png', url: ''}


social:
- {icon: 'github', link: 'https://github.com/LeNPaul'}
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}

contacts:
- {name: 'Kevin ZHAO Weiming', title: 'Head of Class', department: 'SJTU AIGC Class', institution: 'Shanghai Jiao Tong University', institution_address: '800 Dongchuan Road, Minhang, Shanghai, China', email: 'aigc#sjtu.edu.cn', office: 'Room B300, Student Innovation Center'}
